/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agents_HRTimer */


#ifndef _Included_pplannig_utils_HRTimer
#define _Included_pplannig_utils_HRTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agents_HRTimer
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pplannig_utils_HRTimer_print
  (JNIEnv *, jobject);

/*
 * Class:     agents_HRTimer
 * Method:    getCurrentNanotime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_pplannig_utils_HRTimer_getCurrentNanotime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
