/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_edu_rmit_agtgrp_apparate_utils_HRTimer */

#ifndef _Included_au_edu_rmit_agtgrp_apparate_utils_HRTimer
#define _Included_au_edu_rmit_agtgrp_apparate_utils_HRTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_edu_rmit_agtgrp_apparate_utils_HRTimer
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_au_edu_rmit_agtgrp_apparate_utils_HRTimer_print
  (JNIEnv *, jobject);

/*
 * Class:     au_edu_rmit_agtgrp_apparate_utils_HRTimer
 * Method:    getCurrentNanotime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_au_edu_rmit_agtgrp_apparate_utils_HRTimer_getCurrentNanotime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
